plugins {
    id 'com.android.application'
}

android {
    namespace 'com.cinat.apkhtml'
    compileSdk 34

    signingConfigs {
        release {
            storeFile file('../release.keystore')
            storePassword 'apkHTML2026'
            keyAlias 'apkhtml'
            keyPassword 'apkHTML2026'
        }
    }

    defaultConfig {
        applicationId "com.cinat.apkhtml"
        minSdk 21
        targetSdk 34
        versionCode 5
        versionName "2.1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}